# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
   
    runs-on: [ubuntu-latest]
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --configuration release
    - name: Zip
      run: zip -r Image-Resizer-Azure-Function-${{ github.ref_name }}.zip ./Image-Resizer-Azure-Function/src/ImageResizerFunction/bin/Release/net6.0/publish/.
    - name: Create Release    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Image-Resizer-Azure-Function-${{ github.ref_name }}.zip"
 
